/*
 * 02_Messwerte
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetMessStationDto
    /// </summary>
    [DataContract(Name = "GetMessStationDto")]
    public partial class GetMessStationDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMessStationDto" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="betriebsDauer">betriebsDauer.</param>
        /// <param name="messwerte">messwerte.</param>
        public GetMessStationDto(int id = default(int), string name = default(string), string betriebsDauer = default(string), List<GetMessStationMesswertDto> messwerte = default(List<GetMessStationMesswertDto>))
        {
            this.Id = id;
            this.Name = name;
            this.BetriebsDauer = betriebsDauer;
            this.Messwerte = messwerte;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets BetriebsDauer
        /// </summary>
        [DataMember(Name = "betriebsDauer", EmitDefaultValue = true)]
        public string BetriebsDauer { get; set; }

        /// <summary>
        /// Gets or Sets Messwerte
        /// </summary>
        [DataMember(Name = "messwerte", EmitDefaultValue = true)]
        public List<GetMessStationMesswertDto> Messwerte { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMessStationDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  BetriebsDauer: ").Append(BetriebsDauer).Append("\n");
            sb.Append("  Messwerte: ").Append(Messwerte).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
