/*
 * 02_Messwerte
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetMessStationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMessStationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMessStationDto
        //private GetMessStationDto instance;

        public GetMessStationDtoTests()
        {
            // TODO uncomment below to create an instance of GetMessStationDto
            //instance = new GetMessStationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMessStationDto
        /// </summary>
        [Fact]
        public void GetMessStationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMessStationDto
            //Assert.IsType<GetMessStationDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'BetriebsDauer'
        /// </summary>
        [Fact]
        public void BetriebsDauerTest()
        {
            // TODO unit test for the property 'BetriebsDauer'
        }

        /// <summary>
        /// Test the property 'Messwerte'
        /// </summary>
        [Fact]
        public void MesswerteTest()
        {
            // TODO unit test for the property 'Messwerte'
        }
    }
}
