/*
 * 02_Messwerte
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetMessStationMesswertDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMessStationMesswertDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMessStationMesswertDto
        //private GetMessStationMesswertDto instance;

        public GetMessStationMesswertDtoTests()
        {
            // TODO uncomment below to create an instance of GetMessStationMesswertDto
            //instance = new GetMessStationMesswertDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMessStationMesswertDto
        /// </summary>
        [Fact]
        public void GetMessStationMesswertDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMessStationMesswertDto
            //Assert.IsType<GetMessStationMesswertDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
    }
}
