/*
 * 02_Messwerte
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PostMessStationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostMessStationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostMessStationDto
        //private PostMessStationDto instance;

        public PostMessStationDtoTests()
        {
            // TODO uncomment below to create an instance of PostMessStationDto
            //instance = new PostMessStationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostMessStationDto
        /// </summary>
        [Fact]
        public void PostMessStationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostMessStationDto
            //Assert.IsType<PostMessStationDto>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Betriebsdauer'
        /// </summary>
        [Fact]
        public void BetriebsdauerTest()
        {
            // TODO unit test for the property 'Betriebsdauer'
        }
    }
}
